version: 1
validation: sovereign
default_denom: ubgl
accounts:
- name: alice
  coins:
  - 100000000ubgl
- name: bob
  coins:
  - 100000000ubgl
client:
  openapi:
    path: docs/static/openapi.json
  typescript:
    path: ./ts-client
faucet:
  name: bob
  coins:
  - 10000ubgl
validators:
- name: alice
  bonded: 100000000ubgl
- name: validator1
  bonded: 200000000ubgl
- name: validator2
  bonded: 100000000ubgl